services:

  # ======================
  # MESSAGE BROKER
  # ======================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - micro-net

  # ======================
  # POSTGRES (1 SOLO MOTOR)
  # ======================
  postgres:
    image: postgres:16
    container_name: fintech-postgres
    environment:
      POSTGRES_USER: fabricio
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fabricio"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - micro-net

  # ======================
  # MICROSERVICES
  # ======================

  identity-service:
    build: ./IdentityService
    ports:
      - "5005:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__IdentityConnection=Host=postgres;Port=5432;Database=IdentityDb;Username=fabricio;Password=1234
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - micro-net

  account-service:
    build: ./AccountService
    ports:
      - "5002:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__AccountConnection=Host=postgres;Port=5432;Database=AccountDb;Username=fabricio;Password=1234
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - micro-net

  transaction-service:
    build: ./TransactionService
    ports:
      - "5001:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__TransactionConnection=Host=postgres;Port=5432;Database=TransactionDb;Username=fabricio;Password=1234
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - micro-net

  asset-service:
    build: ./AssetService
    ports:
      - "5004:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__AssetConnection=Host=postgres;Port=5432;Database=AssetDb;Username=fabricio;Password=1234
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - micro-net

  audit-service:
    build: ./AuditService
    ports:
      - "5003:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__AuditConnection=Host=postgres;Port=5432;Database=AuditDb;Username=fabricio;Password=1234
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - micro-net

# ======================
# VOLUMES
# ======================
volumes:
  pgdata:

# ======================
# NETWORKS
# ======================
networks:
  micro-net:
    driver: bridge
